INSERT INTO accounts (date, user_uid, first_name, last_name, suffix, user_pwd, user_level, email_address, department, head, section) VALUES
(current_timestamp(),'GP-20-688','Alyssa Jenine','Prudente','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Gemma Calalo','Health Benefits'),
(current_timestamp(),'GP-19-684','Christian','Ragel','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-19-685','Nifran','Delos Reyes','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Elmer Bautista',''),
(current_timestamp(),'GP-19-682','Jypzy','Abad','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-19-683','Lenlyn','Marcilla','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Gemma Calalo','Health Benefits'),
(current_timestamp(),'GP-20-696','Abigail','Manaois','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-20-694','Jenirose','Barasi','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW200'),
(current_timestamp(),'GP-20-697','Jommel','Mission','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-20-693','Alvin Jhon','Arroyo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-20-700','Jerevie','Sabacan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW50'),
(current_timestamp(),'GP-20-701','John Yori','Tagle','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-20-695','Richard','Gerpacio','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-20-699','Arnie','Paras','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-20-698','Danny','Ocsin','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-20-692','John Martin','Aricayos','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-15-454','Richard','Tating','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-10-244','Deserie','Yacon','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-12-356','Francisco','Ramirez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','FEM'),
(current_timestamp(),'GP-08-232','Melly Jenna','Arive','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Accounting','Gerina Beri',''),
(current_timestamp(),'GP-12-329','Jeany Lynn','Bucayan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW150'),
(current_timestamp(),'GP-94-005','Raymond','Reyes','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Quality Assurance','Raymond Reyes',''),
(current_timestamp(),'GP-12-327','Melvin','Lazaga','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Akira Toku','wh'),
(current_timestamp(),'GP-19-653','Tomoyuki','Ozawa','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Akira Toku',''),
(current_timestamp(),'GP-20-691','Akira','Toku','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','President','',''),
(current_timestamp(),'GP-11-306','Jonathan','Nemedez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Administration','Gemma Calalo',''),
(current_timestamp(),'GP-15-431','Mydel','Genise','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-17-544','Grethsell','Dela Cuesta','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-13-366','Karen','Roque','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-18-599','Mary Rose','Mendoza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-13-376','Crispin','Mendoza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-10-249','Dail Eireann','Bartolata','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-578','Mary Grace','Vargas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-14-384','Michael','Genise','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-21-708','Shigeyuki','Fukunaga','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-21-710','Fumiya','Kojima','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Accounting','Akira Toku',''),
(current_timestamp(),'GP-01-130','Rhea Liza','Dularte','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle','PU'),
(current_timestamp(),'GP-06-185','Gerina','Beri','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Accounting','Akira Toku',''),
(current_timestamp(),'GP-11-305','Rio','Monzon','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Administration','Gemma Calalo',''),
(current_timestamp(),'GP-11-277','Nolieson','Catigan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Production Technology','',''),
(current_timestamp(),'GP-16-480','Ranelyn','Castro','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Technology','Nolieson Catigan',''),
(current_timestamp(),'GP-14-409','Anjelica','Mendoza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Technology','Nolieson Catigan',''),
(current_timestamp(),'GP-07-202','Carlito','Magpatoc','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Technology','Nolieson Catigan',''),
(current_timestamp(),'GP-18-581','Roan Mae','Bermas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Technology','Nolieson Catigan',''),
(current_timestamp(),'GP-14-393','Bernadette','Nazareno','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-16-472','Susan','Monterde','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-12-352','Orlando','Manalo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-19-672','Princess','Pauni','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-10-268','Idhonnah','Yalung','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-18-638','Leahflor','Maligsa','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-18-576','Leonardo','Abueni','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-17-535','Marson','Abito','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-12-359','Julius Cezar','Tamayo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-18-628','Marvin','Bernardo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-15-429','Antonieta','Gawaran','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-17-505','Maricel','Aydalla','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-14-406','Myr Joy','De Mesa','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-17-548','Mary Jane','Dela Vega','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-12-347','Eric','Florindo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-19-664','Kevin','Guevarra','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-17-529','Jacinto','Corpuz','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-18-596','John Eric','Mugas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-16-473','Lorie','Nacor','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-08-215','Oscar','Asuelo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','',''),
(current_timestamp(),'GP-19-659','Rose Bella','Austria','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-17-541','Sherilyn','Barron','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-13-365','Precious Mae','Cudiamat','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-10-247','Digna','Gonzales','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-17-550','Annalyn','Pagatpat','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-98-079','Cherry','Pinpin','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-16-476','Jinelyn','Sabejon','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-18-646','Justine Joyce','Saliva','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-16-477','Jizelle','Tolaldo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Support','Oscar Asuelo',''),
(current_timestamp(),'GP-10-248','Sheila','Castuli','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-18-600','Arnold','Raganit','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-07-199','Jonald John','Lapan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-11-285','Loraine','Legaspina','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-18-604','Camille','Tonga','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-14-383','Ian Roy','Gabito','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-01-125','Genny','Desacula','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-15-422','Michael','Ardiente','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-12-322','Emil','Alvarez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-18-606','Nemfa','Villanroque','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-03-158','Lyziel','Semillano','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-21-707','Jason','Bautista','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-14-381','Nerio','Gelle','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-08-220','Joel','Naranjo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle','PU'),
(current_timestamp(),'GP-17-523','Rinalyn','Dulce','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Gemma Calalo','General Services'),
(current_timestamp(),'GP-18-616','Charisse','Mendoza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Rio Monzon','Human Resources'),
(current_timestamp(),'GP-19-678','Rusitha Audrey','Bornasal','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Rio Monzon','Human Resources'),
(current_timestamp(),'GP-17-571','Felmhar','Vivo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','MIS'),
(current_timestamp(),'GP-18-614','Tricy Ann','Escamillas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','FEM'),
(current_timestamp(),'GP-05-163','Gabriel','Villegas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','FEM'),
(current_timestamp(),'GP-16-478','John Carlo','Sierra','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','FEM'),
(current_timestamp(),'GP-06-188','Alex','Gutib','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Rinalyn Dulce','General Services'),
(current_timestamp(),'GP-17-516','Jonathan Jr.','Natuel','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','FEM'),
(current_timestamp(),'GP-16-461','John Lord','Alonzo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Rio Monzon','Human Resources'),
(current_timestamp(),'GP-14-418','Myra Flor','Gonzales','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Accounting','Gerina Beri',''),
(current_timestamp(),'GP-07-206','Maria Carmen','Macob','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Accounting','Gerina Beri',''),
(current_timestamp(),'GP-07-196','Maricel','Montano','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Accounting','Gerina Beri',''),
(current_timestamp(),'GP-15-442','Krizel Micah Anne','Alvarez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Assurance','Raymond Reyes','EOSH'),
(current_timestamp(),'GP-14-397','Arlene','Lontoc','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Assurance','Raymond Reyes','DCC'),
(current_timestamp(),'GP-20-702','Carmela','Jordan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Assurance','Raymond Reyes','EOSH'),
(current_timestamp(),'GP-15-449','Melody','Odviar','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-18-639','Cherry Rose','Manalon','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-13-372','Joey','Comia','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-14-388','John Moroni','Pagulayan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-19-661','Laila','Boluso','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-18-627','Alvin','Benavente','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-17-522','Jeshaydel','Villaraza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-14-382','Ramina','Miguel','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-16-471','Renalyn','Mogol','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-17-557','Jonel','Llacona','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','','',''),
(current_timestamp(),'GP-02-145','Brenisa','Domingo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-18-613','NiÃ±o','Torres','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-14-419','Merrelyn','Bantugan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-17-510','Noriza','Cruz','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-16-490','Rosemarie Jinky','Manalo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-18-632','Ivy','Del Mundo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-14-417','Catherine','Marcelo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-08-222','Jesper','Odasco','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-19-665','Luche','Labanza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-12-321','Benjie','Paras','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-10-269','Sheryll','Ramirez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Production Planning and Inventory Control','',''),
(current_timestamp(),'GP-01-132','Chona','Cortez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-97-064','Luisa','Palomeras','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-15-426','Naomi','Calderon','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-17-564','Dechristine','Plata','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-18-595','Marlyn','Mendez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-18-609','Allelie','Centeno','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-21-709','Abigail','Torres','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-21-714','Eries','Cabrera','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-11-278','Mary Jane','Pacuan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','impex'),
(current_timestamp(),'GP-11-299','Mario','Laforteza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','impex'),
(current_timestamp(),'GP-99-069','Nestor','Umali','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-00-098','Elarde','Mendoza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-19-679','Klarence','Santiago','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','impex'),
(current_timestamp(),'GP-18-610','Ernald','Fagutan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','impex'),
(current_timestamp(),'GP-18-612','Jaypee','Mercado','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Direct Operation Kaizen','Elmer Bautista',''),
(current_timestamp(),'GP-18-611','Francisco','Lozano','Jr.','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Direct Operation Kaizen','Elmer Bautista',''),
(current_timestamp(),'GP-97-059','Elmer','Bautista','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Direct Operation Kaizen','Elmer Bautista',''),
(current_timestamp(),'GP-07-209','Hermano','Herrera','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Direct Operation Kaizen','Elmer Bautista',''),
(current_timestamp(),'GP-10-271','Shermayne','Cosa','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','System Kaizen','Tomoyuki Ozawa',''),
(current_timestamp(),'GP-18-577','Jackelyn','Ade','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-513','Josyl','Espino','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-14-416','Pamela','Umali','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-14-415','Maria Novy','Tayco','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-16-470','Andy','Manangu','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-13-361','Shiela','Alinio','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-01-115','Wilma','Logrono','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-06-178','Bobby','Didal','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-01-116','Nolsan','Ciudad','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-06-190','Filipina','Alcantara','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-514','Ada','Ferros','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-631','Mary Loise','Cataggatan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-15-443','Jenevieve Anne','Araza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-16-493 ','Leo','Moreno','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-626','Jazzydee','Baong','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-590','Ernaliza','Libria','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-19-657','Daisy','Alvaran','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-570','Wila','Tomas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-542','Mark Joseph','Camay','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-19-675','Louie','Umali','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-517','Rona Mhay','Beig','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-16-485','Divina','Corod','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-11-287','Rosalyn','Aquino','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-579','Ryan Boy','Alejandro','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-02-151','Liezel','Manlapaz','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-97-058','Marissa','Tahimic','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-597','Joseph','Onias','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-592','Ginalyn','Manalo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-19-668','Edna','Macaranas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-507','Joseph','Beig','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-16-486','Ria','Corpus','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-18-647','Annavi Katrina','Sarmiento','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-10-243','Lilybeth','Arguelles','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-12-324','Mary Ann','Delgado','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-12-323','Joanna Marie','Moises','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-11-282','Cecille','PeleÃ±o','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-12-345','Haydee','Custodio','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-19-663','Leonardo','De La Cruz','Jr.','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-518','Lucito','Onsana','Jr.','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-12-350','Marvin','Ilao','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-12-330','Ruben','Delgado','Jr.','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-14-385','Izyl','Pimentel','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-97-055','Dina','Lisboa','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-16-466','Hazel Ann','Dela Torre','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-10-262','Noemi','Rojas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-16-469','Jinky','Jaurigue','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-10-251','Jacquelyn','De Roxas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-561','Romay','Manuel','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-508','Roldan','Bencito','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-19-673','Andy William','Perreras','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-19-671','Jerick','Mirandilla','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-12-340','Aris','Cabuyao','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','Saitama'),
(current_timestamp(),'GP-08-216','Wennie','Naungayan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-08-214','Rey','Armillo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-15-438','Edwin','Tolentino','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-07-205','Krislyn','Brillantes','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-07-204','Emria','Sarte','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-18-587','Diana','Ferrer','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-12-344','Chareyna','Ramos','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-08-225','Jonalyn','Rivamonte','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-18-625','Madelyn','Baldrias','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-16-484','Beverly','Capitle','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-00-109','Elma','Culla','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-18-630','Glenda','Casalme','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW150'),
(current_timestamp(),'GP-18-650','Jhoezalyn','Taller','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW150'),
(current_timestamp(),'GP-16-488','Ian Jay','Jacobo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW150'),
(current_timestamp(),'GP-18-623','Edlyn','Aliscad','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-536','John Simon','Aguilar','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-546','Julian','Cueto','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-558','Erica Joy','Llagas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-18-605','John Jeffrey','Ventigan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-506','Christian','Baldonado','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-16-463','Melanie','Bagon','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-14-403','Donalyn','Robledo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-10-257','Leivic','Luig','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-11-289','Margie','Umali','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-18-588','Adrian Kelvin','Grepo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-19-674','Elsie','Sinsay','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-17-520','Cristelyn','Sencil','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-11-283','Merry Beth','Cinco','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-12-346','Cherrylyn','Deseo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-12-358','Juvilyn','Dela Cruz','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-05-167','Reynaldo','Vildal','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','Saitama'),
(current_timestamp(),'GP-02-149','Lemuel','Semillano','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-08-224','Joy','Quilantang','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-12-343','Wenna Rose','Cornejo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW10'),
(current_timestamp(),'GP-08-228','Marilyn','Tondeng','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW200'),
(current_timestamp(),'GP-02-142','Dana','PeliÃ±a','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-10-250','Deserie','Baldesino','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-12-335','Ronel','Alisangco','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-06-193','Michael','Villasanta','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW100'),
(current_timestamp(),'GP-10-246','Fernaliza','Bernal','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW100'),
(current_timestamp(),'GP-12-351','Eva','Evangelista','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','UD700'),
(current_timestamp(),'GP-07-210','Jonar','Mojica','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-17-521','Jasune','Vargas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-14-408','Aris','Jose','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-17-504','Angel','Apuro','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-17-567','Ricky','Salvador','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW50'),
(current_timestamp(),'GP-17-560','Jonel','Maganis','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-19-667','Mary Ann','Ludovice','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-13-374','Jaysar','Igaya','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','UD700'),
(current_timestamp(),'GP-17-538','Baby','Atienza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','UD700'),
(current_timestamp(),'GP-17-562','Lenilyn','Merino','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','UD700'),
(current_timestamp(),'GP-13-373','Felina','Hernandez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-17-568','Jenelyn','Sarmiento','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','YRZ'),
(current_timestamp(),'GP-18-602','Angelica','Salvador','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-17-540','Leigee','Baldonado','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SCDM'),
(current_timestamp(),'GP-18-637','Kristine Bea','Bayungan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW50'),
(current_timestamp(),'GP-18-640','Precing','Marasigan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-18-594','Dwendelyn','Maglagui','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW100'),
(current_timestamp(),'GP-17-565','Rosechelle','Riza','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW100'),
(current_timestamp(),'GP-16-495','Armeda','Parohinog','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW100'),
(current_timestamp(),'GP-17-569','Maria Erva','Sosa','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW100'),
(current_timestamp(),'GP-18-591','Renelyn','Linezo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW100'),
(current_timestamp(),'GP-19-670','Marina','Matalog','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-16-497','Resty','Viray','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-13-367','Marissa','Canto','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-18-598','Jameson','Oracion','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW200'),
(current_timestamp(),'GP-16-468','Kristalyn','Herbosana','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW200'),
(current_timestamp(),'GP-16-482','Nietelyn','Alic','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW200'),
(current_timestamp(),'GP-19-655','Charlyn','Alboroto','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-11-291','Ric','Albayda','Jr.','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-18-580','Cris John','Belarmino','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-14-390','Analyn','Cadocoy','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-19-662','Benjie','Calleja','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-17-511','Eric','Cubol','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-16-465','Daniel','Daoayen','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-17-552','Jocelyn','Durango','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-11-313','Cristopher','Galang','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-16-467','Ma. Jesusa','Garcia','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-17-526','Avelino','Gruezo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-16-479','Edmar','Herrera','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-18-635','Reynan','Joya','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-15-421','Maricris','Lerit','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-15-433','Luimerson','Lopez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-11-303','Michelle','Malubay','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-11-304','Richard','Mojica','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-18-585','Fhil Jhon','Eisma','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-14-389','Lauterio','Maguddayao','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-16-474','Carlo','Pedrosa','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-11-301','Roel','Magat','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','FEM'),
(current_timestamp(),'GP-10-260','Shielo','Osoyos','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-17-500','Butch','Pari-an','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-18-644','Reymond','Ramirez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-18-601','Florence','Reguindin','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-12-357','Jaypee','Robas','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-06-181','Ryan','Rolle','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan',''),
(current_timestamp(),'GP-11-309','Sonny','Samson','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-11-292','Raul','Santos','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-11-310','Eloisa','Sapalasan','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Part Production','Eloisa Sapalasan',''),
(current_timestamp(),'GP-11-312','Angelo','Ticong','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-11-314','Christopher','Trajico','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan',''),
(current_timestamp(),'GP-02-141','Melvin','Beltran','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan',''),
(current_timestamp(),'GP-15-446','Phillip','Cabuco','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-17-515','Kevin','Hallig','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-17-553','Jake Hanzel','Eballar','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-18-643','Jorlan','Palma','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-18-603','Joven','San Miguel','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-16-494','Ryan Niel','Nocon','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-18-624','Jayson','Aroma','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-18-649','Mark Marris','Astillero','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-11-294','Riza','Becios','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-17-566','Glen','Salgado','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-22-717','Jonnalyn','Maigue','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-22-716','Ace','Loyola','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','impex'),
(current_timestamp(),'GP-18-634','Raymond','Due','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','wh'),
(current_timestamp(),'GP-02-146','Jacqueline','Servida','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Purchasing','Nerio Gelle',''),
(current_timestamp(),'GP-22-718','Antonio','Negrite','Jr.','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','FEM'),
(current_timestamp(),'GP-22-719','Rodil','Santiago','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','pm'),
(current_timestamp(),'GP-22-720','Jayson','Torres','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Assurance','Raymond Reyes',''),
(current_timestamp(),'GP-22-721','Tetsuya','Hatozaki','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan',''),
(current_timestamp(),'GP-22-722','Cedrick James','Orozo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','MIS'),
(current_timestamp(),'GP-22-723','Clarissa','Bigalbal','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-22-724','Perry Boy','Boco','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan',''),
(current_timestamp(),'GP-22-725','Nicole','Bucod','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-22-726','Robert','Cabangunay','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-22-727','Nicole','Domingo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW50'),
(current_timestamp(),'GP-22-728','Marissa','Magbuo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Parts Inspection','Benjie Paras',''),
(current_timestamp(),'GP-22-729','Kevin Roy','Marero','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','MIS'),
(current_timestamp(),'GP-22-730','Ralph Gabriel','Parma','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Jonathan Nemedez','FEM'),
(current_timestamp(),'GP-22-731','Fedie','Sierra','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-22-732','Cecilia','Silang','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBW50'),
(current_timestamp(),'GP-22-733','Jerome','Taganna','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','GLR100'),
(current_timestamp(),'GP-22-734','Jomalyn','Viscarra','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-512','Jessa','Escultura','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Technology','Nolieson Catigan',''),
(current_timestamp(),'GP-15-430','Lalaine','San Lorenzo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-15-450','Maricar','Olivarez','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-13-377','Jezel','Ogatis','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','SDRB100'),
(current_timestamp(),'GP-13-375','Judy','Magpatoc','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-11-308','Irene','Olaes','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-16-489','Michelle','Llamera','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Fabrication'),
(current_timestamp(),'GP-14-405','Dolores','Castro','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Direct Operation Kaizen','Elmer Bautista',''),
(current_timestamp(),'GP-16-475','Genie','Rogador','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','RBG'),
(current_timestamp(),'GP-17-545','Catherine','Cruz','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','','BRM'),
(current_timestamp(),'GP-22-715','Jennielaine','Lapurga','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Assurance','Raymond Reyes',''),
(current_timestamp(),'GP-22-735','Meriole Nickky','Lipata','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production','',''),
(current_timestamp(),'GP-22-736','Elaine','Sangalang','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Gemma Calalo','General Services'),
(current_timestamp(),'GP-10-273','Gemma','Calalo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','head','','Administration','Akira Toku',''),
(current_timestamp(),'GP-22-738','Joy Christian','Pareja','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Accounting','Gerina Beri',''),
(current_timestamp(),'GP-22-737','Sherelyn','Bunag','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Production Planning and Inventory Control','Sheryll Ramirez','impex'),
(current_timestamp(),'GP-15-435','Rogina','Menorca','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-543','Catherine','Castillo','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Quality Control','Wilma Logrono',''),
(current_timestamp(),'GP-17-509','Jacquelyn','Gabato','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan',''),
(current_timestamp(),'GP-12-342','Aires Joy','Lasala','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Part Production','Eloisa Sapalasan','Molding'),
(current_timestamp(),'GP-15-437','Rose Ann','Alega','','$2y$10$SipVso5StD.vPmtm7rIfKOzgvozIxvKZGs9k0gzdSGlsAO/Z2nPWC','user','','Administration','Rio Monzon','Human Resources');
